package forms;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.UIManager;

public class Simulacions extends javax.swing.JPanel {
    
    int seg;
    
    Thread tiempollenado = new Thread(){
        public void run(){
            try{
                for(seg = 0; seg<=100; seg++){
                    reservorio.setValue(seg);
                    tiempollenado.sleep(100);
                }
            }catch(Exception e){
            }
        }
    };
    Thread tiempotubollenado = new Thread(){
        public void run(){
            try{
                for(int i=1; i<=100; i++){
                    tubollenado.setValue(i);
                    tiempotubollenado.sleep(1);
                }
            }catch(Exception e){
            }
        }
    };
    Thread tiempovaciado = new Thread(){
        public void run(){
            try{
                for(int i=seg; i>=0; seg--){
                    reservorio.setValue(seg);
                    tiempovaciado.sleep(100);
                    if(seg==0){
                       tubovaciado.setValue(0); 
                    }
                }
            }catch(Exception e){
            }
        }
    };
    
    Thread tiempotubovaciado = new Thread(){
        public void run(){
            try{
                for(int i=1; i<=100; i++){
                    tubollenado.setValue(0);
                    tubovaciado.setValue(i);
                    tiempotubovaciado.sleep(1);
                }
            }catch(Exception e){
            }
        }
    };

    public Simulacions() {
        initComponents();
        UIManager.put( "nimbusOrange", new Color(   38, 139, 210 ) );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reservorio = new javax.swing.JProgressBar();
        tubollenado = new javax.swing.JProgressBar();
        tubovaciado = new javax.swing.JProgressBar();
        botonllenado = new javax.swing.JButton();
        botonvaciado = new javax.swing.JButton();
        fondosimu = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reservorio.setOrientation(1);
        reservorio.setPreferredSize(new java.awt.Dimension(146, 250));
        reservorio.setRequestFocusEnabled(false);
        add(reservorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 170, 259));

        tubollenado.setPreferredSize(new java.awt.Dimension(146, 25));
        add(tubollenado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 120, -1));

        tubovaciado.setPreferredSize(new java.awt.Dimension(146, 25));
        add(tubovaciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 110, -1));

        botonllenado.setText("Llenado");
        botonllenado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonllenadoActionPerformed(evt);
            }
        });
        add(botonllenado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        botonvaciado.setText("Vaciado");
        botonvaciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonvaciadoActionPerformed(evt);
            }
        });
        add(botonvaciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        fondosimu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondosimu.png"))); // NOI18N
        add(fondosimu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void botonllenadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonllenadoActionPerformed
        tiempollenado.start();
        botonllenado.setVisible(false);
        tiempotubollenado.start();
    }//GEN-LAST:event_botonllenadoActionPerformed

    private void botonvaciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonvaciadoActionPerformed
        tiempovaciado.start();
        botonvaciado.setVisible(false);
        tiempotubovaciado.start();
    }//GEN-LAST:event_botonvaciadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonllenado;
    private javax.swing.JButton botonvaciado;
    private javax.swing.JLabel fondosimu;
    private javax.swing.JProgressBar reservorio;
    private javax.swing.JProgressBar tubollenado;
    private javax.swing.JProgressBar tubovaciado;
    // End of variables declaration//GEN-END:variables
  
}
